CREATE TABLE IF NOT EXISTS renting_transaction (
    renting_transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    renting_date DATE,
    total_price NUMERIC(19, 2),
    customer_id BIGINT,
    reservation_token VARCHAR(255),
    renting_status VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS renting_detail (
    renting_detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    renting_transaction_id BIGINT,
    car_id BIGINT,
    start_date DATE,
    end_date DATE,
    price NUMERIC(19, 2),
    CONSTRAINT fk_renting_detail_transaction FOREIGN KEY (renting_transaction_id) REFERENCES renting_transaction (renting_transaction_id)
);

CREATE TABLE IF NOT EXISTS saga_compensation_failure (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_id BIGINT,
    reservation_token VARCHAR(255),
    operation VARCHAR(255),
    reason VARCHAR(1000),
    created_at TIMESTAMP
);
