CREATE TABLE IF NOT EXISTS renting_transaction (
    renting_transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    renting_date DATE,
    total_price NUMERIC(19, 2),
    customer_id BIGINT,
    renting_status VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS renting_detail (
    renting_detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    renting_transaction_id BIGINT,
    car_id BIGINT,
    start_date DATE,
    end_date DATE,
    price NUMERIC(19, 2),
    CONSTRAINT fk_renting_detail_transaction FOREIGN KEY (renting_transaction_id) REFERENCES renting_transaction (renting_transaction_id)
);

INSERT INTO renting_transaction (renting_transaction_id, renting_date, total_price, customer_id, renting_status)
SELECT 1, DATE '2026-07-01', 1200000.00, 1, 'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM renting_transaction WHERE renting_transaction_id = 1);

INSERT INTO renting_transaction (renting_transaction_id, renting_date, total_price, customer_id, renting_status)
SELECT 2, DATE '2026-07-05', 800000.00, 2, 'APPROVED'
WHERE NOT EXISTS (SELECT 1 FROM renting_transaction WHERE renting_transaction_id = 2);

INSERT INTO renting_transaction (renting_transaction_id, renting_date, total_price, customer_id, renting_status)
SELECT 3, DATE '2026-07-10', 1500000.00, 3, 'PENDING'
WHERE NOT EXISTS (SELECT 1 FROM renting_transaction WHERE renting_transaction_id = 3);

INSERT INTO renting_detail (renting_detail_id, renting_transaction_id, car_id, start_date, end_date, price)
SELECT 1, 1, 1, DATE '2026-07-01', DATE '2026-07-03', 1200000.00
WHERE NOT EXISTS (SELECT 1 FROM renting_detail WHERE renting_detail_id = 1);

INSERT INTO renting_detail (renting_detail_id, renting_transaction_id, car_id, start_date, end_date, price)
SELECT 2, 2, 2, DATE '2026-07-06', DATE '2026-07-07', 800000.00
WHERE NOT EXISTS (SELECT 1 FROM renting_detail WHERE renting_detail_id = 2);

INSERT INTO renting_detail (renting_detail_id, renting_transaction_id, car_id, start_date, end_date, price)
SELECT 3, 3, 4, DATE '2026-07-12', DATE '2026-07-14', 900000.00
WHERE NOT EXISTS (SELECT 1 FROM renting_detail WHERE renting_detail_id = 3);

INSERT INTO renting_detail (renting_detail_id, renting_transaction_id, car_id, start_date, end_date, price)
SELECT 4, 3, 6, DATE '2026-07-12', DATE '2026-07-14', 600000.00
WHERE NOT EXISTS (SELECT 1 FROM renting_detail WHERE renting_detail_id = 4);

ALTER TABLE renting_transaction ALTER COLUMN renting_transaction_id RESTART WITH 4;
ALTER TABLE renting_detail ALTER COLUMN renting_detail_id RESTART WITH 5;
