CREATE TABLE IF NOT EXISTS saga_compensation_failure (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_id BIGINT,
    reservation_token VARCHAR(255),
    operation VARCHAR(255),
    reason VARCHAR(1000),
    created_at TIMESTAMP
);
