CREATE TABLE IF NOT EXISTS manufacturers (
    manufacturer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manufacturer_name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    manufacturer_country VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS suppliers (
    supplier_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_name VARCHAR(255) NOT NULL,
    supplier_description VARCHAR(255),
    supplier_address VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS car_information (
    car_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_name VARCHAR(255),
    car_description VARCHAR(255),
    number_of_doors INTEGER NOT NULL,
    seating_capacity INTEGER NOT NULL,
    fuel_type VARCHAR(255),
    manufacturing_year INTEGER NOT NULL,
    car_status VARCHAR(255),
    manufacturer_id BIGINT,
    supplier_id BIGINT,
    CONSTRAINT fk_car_information_manufacturer FOREIGN KEY (manufacturer_id) REFERENCES manufacturers (manufacturer_id),
    CONSTRAINT fk_car_information_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers (supplier_id)
);

INSERT INTO manufacturers (manufacturer_id, manufacturer_name, description, manufacturer_country)
SELECT 1, 'Toyota', 'Reliable passenger cars and hybrids', 'Japan'
WHERE NOT EXISTS (SELECT 1 FROM manufacturers WHERE manufacturer_id = 1);

INSERT INTO manufacturers (manufacturer_id, manufacturer_name, description, manufacturer_country)
SELECT 2, 'Honda', 'Compact cars and family vehicles', 'Japan'
WHERE NOT EXISTS (SELECT 1 FROM manufacturers WHERE manufacturer_id = 2);

INSERT INTO manufacturers (manufacturer_id, manufacturer_name, description, manufacturer_country)
SELECT 3, 'Hyundai', 'Modern cars for city and travel', 'South Korea'
WHERE NOT EXISTS (SELECT 1 FROM manufacturers WHERE manufacturer_id = 3);

INSERT INTO manufacturers (manufacturer_id, manufacturer_name, description, manufacturer_country)
SELECT 4, 'VinFast', 'Vietnamese electric vehicle manufacturer', 'Vietnam'
WHERE NOT EXISTS (SELECT 1 FROM manufacturers WHERE manufacturer_id = 4);

INSERT INTO suppliers (supplier_id, supplier_name, supplier_description, supplier_address)
SELECT 1, 'FPT Rental Center', 'Main car rental supplier', 'Hoa Lac Hi-Tech Park, Hanoi'
WHERE NOT EXISTS (SELECT 1 FROM suppliers WHERE supplier_id = 1);

INSERT INTO suppliers (supplier_id, supplier_name, supplier_description, supplier_address)
SELECT 2, 'Saigon Auto Partner', 'Southern region car supplier', 'District 1, Ho Chi Minh City'
WHERE NOT EXISTS (SELECT 1 FROM suppliers WHERE supplier_id = 2);

INSERT INTO suppliers (supplier_id, supplier_name, supplier_description, supplier_address)
SELECT 3, 'Da Nang Mobility', 'Central region car supplier', 'Hai Chau, Da Nang'
WHERE NOT EXISTS (SELECT 1 FROM suppliers WHERE supplier_id = 3);

INSERT INTO car_information (car_id, car_name, car_description, number_of_doors, seating_capacity, fuel_type, manufacturing_year, car_status, manufacturer_id, supplier_id)
SELECT 1, 'Toyota Vios 2023', 'Economy sedan for city trips', 4, 5, 'GASOLINE', 2023, 'AVAILABLE', 1, 1
WHERE NOT EXISTS (SELECT 1 FROM car_information WHERE car_id = 1);

INSERT INTO car_information (car_id, car_name, car_description, number_of_doors, seating_capacity, fuel_type, manufacturing_year, car_status, manufacturer_id, supplier_id)
SELECT 2, 'Honda City 2022', 'Compact sedan with good fuel economy', 4, 5, 'GASOLINE', 2022, 'AVAILABLE', 2, 1
WHERE NOT EXISTS (SELECT 1 FROM car_information WHERE car_id = 2);

INSERT INTO car_information (car_id, car_name, car_description, number_of_doors, seating_capacity, fuel_type, manufacturing_year, car_status, manufacturer_id, supplier_id)
SELECT 3, 'Hyundai Accent 2021', 'Comfortable sedan for daily rental', 4, 5, 'GASOLINE', 2021, 'RENTED', 3, 2
WHERE NOT EXISTS (SELECT 1 FROM car_information WHERE car_id = 3);

INSERT INTO car_information (car_id, car_name, car_description, number_of_doors, seating_capacity, fuel_type, manufacturing_year, car_status, manufacturer_id, supplier_id)
SELECT 4, 'VinFast VF e34 2023', 'Electric SUV for local travel', 5, 5, 'ELECTRIC', 2023, 'AVAILABLE', 4, 2
WHERE NOT EXISTS (SELECT 1 FROM car_information WHERE car_id = 4);

INSERT INTO car_information (car_id, car_name, car_description, number_of_doors, seating_capacity, fuel_type, manufacturing_year, car_status, manufacturer_id, supplier_id)
SELECT 5, 'Toyota Innova 2020', 'Seven-seat MPV for family trips', 5, 7, 'GASOLINE', 2020, 'MAINTENANCE', 1, 3
WHERE NOT EXISTS (SELECT 1 FROM car_information WHERE car_id = 5);

INSERT INTO car_information (car_id, car_name, car_description, number_of_doors, seating_capacity, fuel_type, manufacturing_year, car_status, manufacturer_id, supplier_id)
SELECT 6, 'Honda CR-V Hybrid 2024', 'Hybrid SUV for long distance travel', 5, 5, 'HYBRID', 2024, 'AVAILABLE', 2, 3
WHERE NOT EXISTS (SELECT 1 FROM car_information WHERE car_id = 6);

ALTER TABLE manufacturers ALTER COLUMN manufacturer_id RESTART WITH 5;
ALTER TABLE suppliers ALTER COLUMN supplier_id RESTART WITH 4;
ALTER TABLE car_information ALTER COLUMN car_id RESTART WITH 7;
