CREATE TABLE IF NOT EXISTS manufacturers (
    manufacturer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manufacturer_name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    manufacturer_country VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS suppliers (
    supplier_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_name VARCHAR(255) NOT NULL,
    supplier_description VARCHAR(255),
    supplier_address VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS car_information (
    car_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_name VARCHAR(255),
    car_description VARCHAR(255),
    number_of_doors INTEGER NOT NULL,
    seating_capacity INTEGER NOT NULL,
    fuel_type VARCHAR(255),
    manufacturing_year INTEGER NOT NULL,
    car_status VARCHAR(255),
    reservation_token VARCHAR(255),
    manufacturer_id BIGINT,
    supplier_id BIGINT,
    CONSTRAINT fk_car_information_manufacturer FOREIGN KEY (manufacturer_id) REFERENCES manufacturers (manufacturer_id),
    CONSTRAINT fk_car_information_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers (supplier_id)
);
