CREATE TABLE IF NOT EXISTS customer (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(255),
    telephone VARCHAR(255),
    email VARCHAR(255),
    customer_birthday VARCHAR(255),
    customer_status VARCHAR(255),
    password VARCHAR(255)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_customer_email ON customer (email);

INSERT INTO customer (customer_id, customer_name, telephone, email, customer_birthday, customer_status, password)
SELECT 1, 'Nguyen Van An', '0901000001', 'an.nguyen@example.com', '1998-04-12', 'ACTIVE', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
WHERE NOT EXISTS (SELECT 1 FROM customer WHERE customer_id = 1);

INSERT INTO customer (customer_id, customer_name, telephone, email, customer_birthday, customer_status, password)
SELECT 2, 'Tran Thi Binh', '0901000002', 'binh.tran@example.com', '1999-08-21', 'ACTIVE', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
WHERE NOT EXISTS (SELECT 1 FROM customer WHERE customer_id = 2);

INSERT INTO customer (customer_id, customer_name, telephone, email, customer_birthday, customer_status, password)
SELECT 3, 'Le Minh Chau', '0901000003', 'chau.le@example.com', '1997-11-05', 'ACTIVE', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
WHERE NOT EXISTS (SELECT 1 FROM customer WHERE customer_id = 3);

INSERT INTO customer (customer_id, customer_name, telephone, email, customer_birthday, customer_status, password)
SELECT 4, 'Pham Quoc Dung', '0901000004', 'dung.pham@example.com', '1996-02-17', 'INACTIVE', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
WHERE NOT EXISTS (SELECT 1 FROM customer WHERE customer_id = 4);

INSERT INTO customer (customer_id, customer_name, telephone, email, customer_birthday, customer_status, password)
SELECT 5, 'Hoang Thu Ha', '0901000005', 'ha.hoang@example.com', '2000-06-30', 'BANNED', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'
WHERE NOT EXISTS (SELECT 1 FROM customer WHERE customer_id = 5);

ALTER TABLE customer ALTER COLUMN customer_id RESTART WITH 6;
