CREATE TABLE IF NOT EXISTS customer (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(255),
    telephone VARCHAR(255),
    email VARCHAR(255),
    customer_birthday VARCHAR(255),
    customer_status VARCHAR(255),
    password VARCHAR(255)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_customer_email ON customer (email);
